#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\033[01;33mPARA QUE O BOT ENVIE SEU APK PARA O TESTE\033[0m"
    echo -e "\033[01;33mCOLOQUE SEU APLICATIVO NA SUA VPS COM NOME \033[01;37m base.apk\033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\E[44;1;37m     ATIVACÃO BOT SSH TESTE     \E[0m"
    echo ""
    echo -ne "\n\033[1;32mINFORME O TOKEN\033[1;37m: "
    read token
    clear
    echo ""
    echo -e "\033[1;32mINICIANDO BOT TESTE \033[0m\n"
    cd $HOME/BOT
    rm -rf $HOME/BOT/botssh
    wget https://raw.githubusercontent.com/Lockednet/BT/main/botssh >/dev/null 2>&1
    rm -rf $HOME/ShellBot.sh
    wget https://raw.githubusercontent.com/Lockednet/BT/main/ShellBot.sh >/dev/null 2>&1
    chmod 777 botssh 
    chmod 777 ShellBot.sh
    echo ""
    sleep 1
    screen -dmS bot_teste ./botssh $token > /dev/null 2>&1
    clear
    echo -e "\033[01;32mATIVADO COM SUCESSO\033[0m"
    echo -e "\033[01;37mENTRE NO BOT DIGITE \033[01;36m /start\033[0m"
    sleep 5s
    testebot
} || {
    screen -r -S "bot_teste" -X quit
    clear
    echo -e "\033[01;31mBOT DESATIVADO COM SUCESSO\033[0m"
    sleep 5s
    testebot
}
